stages:
  - check

lint-typecheck-build:
  stage: check
  image: oven/bun:1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - bun install --frozen-lockfile
    - bun run lint
    - bun run typecheck
    - bun run build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

test:
  stage: check
  image: oven/bun:1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - bun install --frozen-lockfile
    - bun test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
